решение 02-components/01-CounterButtonComponent
js-tasks-ru/vue-20201022_yuliya08 pull request #4
Opened 2020-10-31 15:29 UTC by balyasnikova

2020-10-31 15:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по умолчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-31 16:54 UTC, ShGKme requested changes
Изменение `count` родителем не приводит к изменению счётчика на кнопке. Дополнительный параметр `value` и событие `input` не нужны, чтобы добавить компоненту модель. Для этого требуется добавить свойство `model` с описанием параметра и события.

2020-11-02 22:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-11-03 08:15 UTC, ShGKme approved these changes
Все задачи приняты 👍

2020-11-03 08:15 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupInfo.js
> +        <time datetime="2020-01-01">{{ localDate }}</time>
Есть ещё атрибут `datetime`.

2020-11-03 08:15 UTC, merged